---
- name: deploy website into apache webserver
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: enable and ensure apache is started
      ansible.builtin.systemd_service:
        name: apache2
        enabled: yes
        state: started
    - name: ensure unzip is installed
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: download and extract website
      ansible.builtin.unarchive:
        src: https://www.free-css.com/assets/files/free-css-templates/download/page291/goind.zip
        dest: /tmp
        remote_src: yes
    - name: copy the html folder to naukri
      ansible.builtin.copy:
        src: /tmp/html/
        dest: /var/www/html/naukri
        remote_src: yes
